### ISSUE TITLE
Symfony\Component\Process\Exception\ProcessFailedException

### ISSUE THREAD

**Issue by hrishesh** [robertogallea/LaravelPython#2]
Whilre running following issue came.I followed your instructions and in interpreter on laravel-python.php I put my python interpreter. Ran the program and following error arised.
The command "C:\Users\hrish\AppData\Local\Programs\Python\Python39\python.exe "/N/MovieRSystem/public/top_movies.py"" failed. Exit Code: 1(General error) Working directory: D:\N\MovieRSystem\public Output: ================ Error Output: ================ Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python Python runtime state: preinitialized

**Comment by robertogallea** [comment]
Hi,
this issue seems related to your python environment and not to the library itself. Try googling for the exception. I'll close the issue for now. However, if you find out that is related to the library, please feel free to re-open it. Thanks!

**Comment by hrishesh** [comment]
But when I run this it works 
php artisan python:run /path/to/script.py "Some parameter"

**Comment by hrishesh** [comment]
> 
> 
> Hi,
> this issue seems related to your python environment and not to the library itself. Try googling for the exception. I'll close the issue for now. However, if you find out that is related to the library, please feel free to re-open it. Thanks!

But when I run this it works. I don't think there is some issues on my python enviornment
php artisan python:run /path/to/script.py "Some parameter"

**Comment by hrishesh** [comment]
Hello Roberto,
Greetings of the day
Thanks for your reply.
When I run my python script Via command line with an artisan command it
works fine but through Laravel it doesn't. It's been 2-3 days I have been
stuck to this problem. I know the error is not in your side but if you know
any solution to my problem I will be very grateful for it.
Waiting to get a positive response from you.
Regards,
Hrishesh Dhungana
