### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by pexch** [robertogallea/LaravelPython#3]
```
'python' is not recognized as an internal or external command,
operable program or batch file.

 in file C:\Users\admin\Desktop\laravel-api\vendor\robertogallea\laravel-python\src\Services\LaravelPython.php on line 20
```

--------
However, I can run the same command normally, the code is below:
---------

```
$service = new LaravelPython();
$parameters = array($mal->slug, $targetMAL);
$result = $service->run(app_path() . '\Scripts\test.py', $parameters);
```

I have tried to give it the direct python path in the config, but then it says

```
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
Python runtime state: preinitialized
```

**Comment by robertogallea** [comment]
Hi,
this issue seems related to your python environment and not to the library itself. Try googling for the exception. I'll close the issue for now. However, if you find out that is related to the library, please feel free to re-open it. Thanks!

**Comment by FEbrianAtmadhika** [comment]
> ```
> 'python' is not recognized as an internal or external command,
> operable program or batch file.
> 
>  in file C:\Users\admin\Desktop\laravel-api\vendor\robertogallea\laravel-python\src\Services\LaravelPython.php on line 20
> ```
> 
> ## However, I can run the same command normally, the code is below:
> ```
> $service = new LaravelPython();
> $parameters = array($mal->slug, $targetMAL);
> $result = $service->run(app_path() . '\Scripts\test.py', $parameters);
> ```
> 
> I have tried to give it the direct python path in the config, but then it says
> 
> ```
> Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
> Python runtime state: preinitialized
> ```

hei i got the same problem too can somebody help me
